force-app/main/default/objects/ProductExternal__c/ProductExternal__c.object-meta.xml
<CustomObject>
    <label>Product External</label>
    <nameField>
        <label>ProductExternal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products External</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductExternal__c/fields/external_Id__c.field-meta.xml
<CustomField>
    <fullName>external_Id__c</fullName>
    <externalId>true</externalId>
    <label>external Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductExternal__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductSyncBatchTest.cls
@isTest
private class ProductSyncBatchTest {
    @isTest
    static void testProductSyncBatch() {
        Test.setMock(HttpCalloutMock.class, new FakeStoreAPIMock());

        Test.startTest();
        Database.executeBatch(new ProductSyncBatch());
        Test.stopTest();

        List<ProductExternal__c> products = [SELECT External_Id__c, Name, Price__c, Rating__c FROM ProductExternal__c];
        
        System.assertEquals(1, products.size(), 'Debe crearse un producto');
        System.assertEquals('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', products[0].Name, 'El nombre debe coincidir');
        System.assertEquals(109.95, products[0].Price__c, 'El precio debe coincidir');
        System.assertEquals(3.9, products[0].Rating__c, 'El rating debe coincidir');
    }
}