force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OIN-{MM}{DD}{0000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price List</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product_External__c.field-meta.xml
<CustomField>
    <fullName>Product_External__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product External</label>
    <referenceTo>ProductExternal__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductExternal__c/ProductExternal__c.object-meta.xml
<CustomObject>
    <label>Product External</label>
    <nameField>
        <label>ProductExternal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products External</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SaveOrderTotal.cls
public with sharing class SaveOrderTotal {
    public List<Order_Item__c> newOrderItemList;
    
    public SaveOrderTotal(List<Order_Item__c> newOrderItemList){
        this.newOrderItemList = newOrderItemList;
    }
    public void saveOrders(){
        set<Id> productExternalIds = new set<Id>();
        for(Order_Item__c Order_Item : newOrderItemList){
            productExternalIds.add(Order_Item.Product_External__c);
        }
        for(ProductExternal__c productExternal : [SELECT Id, Price__c FROM ProductExternal__c WHERE Id IN :productExternalIds]){
            for(Order_Item__c Order_Item : newOrderItemList){
                if(Order_Item.Product_External__c == productExternal.Id){
                    Order_Item.Price__c = productExternal.Price__c;
                }
            }
        }
    }
}