force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>or-{dd}{mm}{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OIN-{MM}{DD}{0000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price List</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price_changed__c.field-meta.xml
<CustomField>
    <fullName>Price_changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product_External__c.field-meta.xml
<CustomField>
    <fullName>Product_External__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product External</label>
    <referenceTo>ProductExternal__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductExternal__c/ProductExternal__c.object-meta.xml
<CustomObject>
    <label>Product External</label>
    <nameField>
        <label>ProductExternal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products External</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateOrderItems.cls
public class UpdateOrderItems {
    
    public Map<Id, ProductExternal__c> newProductExternalMap;
    
    public UpdateOrderItems(Map<Id, ProductExternal__c> newProductExternalMap){
        this.newProductExternalMap = newProductExternalMap;
    }
    public void updateOrders(){
        
        List<Order_Item__c> orderItemList = new List<Order_Item__c>();
        for(Order_Item__c Order_Item : [SELECT Id, Price__c, Order__c,Product_External__c FROM Order_Item__c WHERE Product_External__c IN :THIS.newProductExternalMap.keyset()]){
            Order_Item.Price__c = THIS.newProductExternalMap.get(Order_Item.Product_External__c).Price__c;
            Order_Item.Price_changed__c = true;
            orderItemList.add(Order_Item);
        }
        update orderItemList;
    }

}